from lexer import lexer  # Lexer from your lexer file
from parser import parser  # Parser from your parser file

def main():
    # Example input that will be lexed and parsed
    test_input = """
    x = 5;
    if (x > 3) {
        y = 10;
    } else {
        y = 0;
    }
    """

    # Step 1: Initialize the lexer with the input
    lexer.input(test_input)

    # Debug: Print tokens generated by the lexer
    print("Tokens generated by the lexer:")
    for token in lexer:
        print(token)

    # Step 2: Parse the input
    result = parser.parse(test_input, lexer=lexer)

    # Output the result of parsing
    print("\nResult of parsing:")
    print(result.pretty_print())

    # Step 3: Generate and print TAC
    tac_list = result.generate_tac()
    print("\nGenerated Three-Address Code (TAC):")
    for tac in tac_list:
        print(tac)

if __name__ == "__main__":
    main()
